# Generated by Django 4.1.2 on 2022-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='News Title')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='News', verbose_name='News Image')),
                ('description', models.TextField(verbose_name='News Description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'News Letters'},
        ),
    ]
