# Generated by Django 4.1.2 on 2022-12-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_whatsnew_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsnew',
            name='content',
            field=models.TextField(default=1, verbose_name='News Content'),
            preserve_default=False,
        ),
    ]
